### ISSUE TITLE
Mapboxの題名タイポ修正

### ISSUE THREAD

**Issue by dayjournal** [MIERUNE/maptiler-sample#4]
Mapboxの題名タイポしているので修正をおこなう。

![スクリーンショット 2021-04-12 16 21 42](https://user-images.githubusercontent.com/7871642/114356770-f231e080-9bab-11eb-90a2-5caf7c69d03d.png)

**Comment by northprint** [comment]
<img width="359" alt="スクリーンショット 2021-04-12 18 51 22" src="https://user-images.githubusercontent.com/45268313/114375951-2911f180-9bc0-11eb-8515-6695dd64aee8.png">

**Comment by northprint** [comment]
修正されました
